"""Seed batch runner — pulls structured_explanations rows, translates,
verifies, writes PASSes to shadow_db.solves, writes FAILs to
shadow_db.seed_failures. Skips clues already processed.

After running, prints a markdown summary report to stdout. After
N batches the catalog can be regenerated by running
extract_catalog.py (which would need extending to read from
shadow_db.solves — separate slice).

Usage:
    python -m prototypes.universal_form_v2.runs.seed_batch [N]

N defaults to 50.
"""
from __future__ import annotations

import json
import sqlite3
import sys
from collections import Counter
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

sys.stdout.reconfigure(encoding="utf-8")

from signature_solver.db import RefDB
from prototypes.universal_form_v2.json_translator import translate_components
from prototypes.universal_form_v2.clipboard_verifier import verify
from prototypes.universal_form_v2.extract_catalog import signature
from prototypes.universal_form_v2.shadow_db import (
    ensure_shadow, write_solve, write_seed_failure, is_clue_processed,
)


def run_batch(n_clues: int, mechanism_filter: str = None) -> dict:
    """Run a seed batch.

    `mechanism_filter` (optional): if given (e.g. 'first_letter'), only
    pulls rows whose components JSON contains a piece with that
    mechanism. Used to target specific kinds of wordplay for focused
    measurement (e.g. measure step-2a's lift on first_letter clues).
    """
    db = RefDB(str(PROJECT_ROOT / "data" / "cryptic_new.db"))
    master = sqlite3.connect(str(PROJECT_ROOT / "data" / "clues_master.db"))
    master.row_factory = sqlite3.Row
    shadow = ensure_shadow()

    # Load existing catalog signatures for "new template" detection
    catalog_path = (PROJECT_ROOT / "prototypes" / "universal_form_v2"
                    / "runs" / "catalog_v1.json")
    with open(catalog_path, encoding="utf-8") as f:
        cat = json.load(f)
    existing_sigs = {e["id"] for e in cat["entries"]}

    # Pull rows. Over-fetch since some will be already processed.
    extra_clause = ""
    extra_params = []
    if mechanism_filter:
        extra_clause = " AND se.components LIKE ?"
        extra_params.append(f'%"mechanism": "{mechanism_filter}"%')
    rows = master.execute(
        f"""
        SELECT se.id AS se_id, se.clue_id, se.components, se.wordplay_types,
               se.definition_text, se.confidence, se.model_version,
               c.source, c.puzzle_number, c.clue_number, c.direction,
               c.clue_text, c.answer
        FROM structured_explanations se
        JOIN clues c ON c.id = se.clue_id
        WHERE c.answer IS NOT NULL AND c.answer != ''
          AND se.components IS NOT NULL AND se.components != ''
          AND se.wordplay_types IN
              ('["charade"]', '["anagram"]', '["hidden"]',
               '["double_definition"]')
          AND se.confidence >= 0.85
          AND c.source NOT IN ('telegraph-toughie', 'cordelia')
          {extra_clause}
        ORDER BY RANDOM()
        LIMIT ?
        """,
        (*extra_params, n_clues * 3),
    ).fetchall()

    stats = Counter()
    sig_counts = Counter()       # signature -> count of PASSes this batch
    new_sigs = {}                # signature -> first answer that produced it
    op_counter = Counter()
    processed = 0

    for r in rows:
        if processed >= n_clues:
            break
        if is_clue_processed(shadow, r["clue_id"]):
            stats["skipped_already_processed"] += 1
            continue

        op = (r["wordplay_types"] or "").strip("[]\"")
        op_counter[op] += 1

        meta = {
            "source": r["source"], "puzzle_number": r["puzzle_number"],
            "clue_number": r["clue_number"], "direction": r["direction"],
            "clue_text": r["clue_text"], "answer": r["answer"],
        }

        form, err = translate_components(r, db)
        if err:
            stats["translation_fail"] += 1
            write_seed_failure(
                shadow, clue_id=r["clue_id"],
                seed_source="structured_explanations",
                failure_kind=err["kind"], failure_detail=err["detail"],
                clue_meta=meta,
                structured_explanation_id=r["se_id"],
                components_json=r["components"])
            processed += 1
            continue

        v = verify(form, r["clue_text"], db)
        if v.verdict == "PASS":
            stats["pass"] += 1
            sig = signature(form.tree)
            sig_counts[sig] += 1
            if sig not in existing_sigs and sig not in new_sigs:
                new_sigs[sig] = r["answer"]
            write_solve(
                shadow, clue_id=r["clue_id"],
                signature=sig, verdict="PASS",
                answer=r["answer"], form_dict=form.to_dict(),
                checks=[c.to_dict() for c in v.checks],
                enrichments=[e.to_dict() for e in v.enrichment_candidates])
        else:
            stats["verifier_fail"] += 1
            fail_detail = "; ".join(
                f"{c.name}: {c.detail}"
                for c in v.checks if c.status == "fail")
            write_seed_failure(
                shadow, clue_id=r["clue_id"],
                seed_source="structured_explanations",
                failure_kind="verifier_fail",
                failure_detail=fail_detail,
                clue_meta=meta,
                structured_explanation_id=r["se_id"],
                components_json=r["components"],
                translated_form=form.to_dict(),
                enrichments=[e.to_dict() for e in v.enrichment_candidates])

        processed += 1

    return {
        "processed": processed, "stats": stats,
        "by_op": op_counter, "sig_counts": sig_counts,
        "new_sigs": new_sigs,
    }


def report(result: dict) -> str:
    lines = []
    lines.append(f"# Seed batch report\n")
    lines.append(f"## Summary")
    lines.append(f"- Processed: **{result['processed']}**")
    s = result["stats"]
    lines.append(f"- PASS:              **{s['pass']}**")
    lines.append(f"- Verifier-FAIL:     {s['verifier_fail']}")
    lines.append(f"- Translation-FAIL:  {s['translation_fail']}")
    if s.get("skipped_already_processed"):
        lines.append(f"- Skipped (already processed): "
                     f"{s['skipped_already_processed']}")
    lines.append("")
    lines.append(f"## By op")
    lines.append("| op | count attempted |")
    lines.append("|---|---|")
    for op, n in result["by_op"].most_common():
        lines.append(f"| {op} | {n} |")
    lines.append("")
    lines.append(f"## NEW signatures discovered: "
                 f"{len(result['new_sigs'])}")
    if result["new_sigs"]:
        for sig, exemplar in sorted(result["new_sigs"].items()):
            count = result["sig_counts"][sig]
            lines.append(f"- `{sig}`  ({count}x; e.g. {exemplar})")
    lines.append("")
    lines.append(f"## Existing signatures reinforced (top 10)")
    lines.append("| signature | new forms this batch |")
    lines.append("|---|---|")
    existing = [(s, n) for s, n in result["sig_counts"].most_common()
                 if s not in result["new_sigs"]]
    for sig, n in existing[:10]:
        lines.append(f"| `{sig}` | {n} |")
    return "\n".join(lines)


def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 50
    mech = sys.argv[2] if len(sys.argv) > 2 else None
    label = f" (mechanism filter: {mech})" if mech else ""
    print(f"Running batch of {n} clues{label}...")
    result = run_batch(n, mechanism_filter=mech)
    print()
    print(report(result))


if __name__ == "__main__":
    main()
